trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: destroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra_deploy'
              backendServiceArm: 'rakeshazurecloud'
              backendAzureRmResourceGroupName: 'sa1_test_eic_trainingRakesh'
              backendAzureRmStorageAccountName: 'rakeshbackendstore'
              backendAzureRmContainerName: 'rakeshtfstate'
              backendAzureRmKey: 'azurerakesh.tfstate'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra_deploy'
              environmentServiceNameAzureRM: 'rakeshazurecloud'